### ISSUE TITLE
HashMap으로 create 할때 id

### ISSUE THREAD

**Issue by JeanPark96** [JeanPark96/Personal_Info_management_SW2018#1]
createContact에서 해쉬맵 키가 id고 이게 local 변수로 선언 했었는데 반복문 돌면서 id값 증가시키면서 추가시키잖아. 근데 이거 전역 변수로 설정해줘야 나중에 다른 메뉴에서 작업하다가 다시 createContact에서 생성 시킬 때 id 겹치지 않고 순차적으로 값이 증가하겠지??

**Comment by jjisol** [comment]
contact랑 appointment랑 todo랑 id 변수 이름을 다 다르게 해줘야지 안 겹칠거같은데? id_contact이런식으로 다 바꾸자

**Comment by JeanPark96** [comment]
근데 id는 키니까 겹칠 염려가 없지 않아?? 다들 다른 클래스고 독립적으로 작동하니까

**Comment by Zeusl** [comment]
음...나는 todolist_id로 해줬어

**Comment by JeanPark96** [comment]
난 id로 냅뒀는데 잘 돌아가긴 해 그래도 키 이름 수정하는게 좋을 것 같긴해서 나중에 3차 과제때까지 키 이름 바꿀게

**Comment by JeanPark96** [comment]
닫힌 이슈에 대해서도 댓글 달리려나...
