### ISSUE TITLE
scanner.nextLine();사용시 주의할점

### ISSUE THREAD

**Issue by jjisol** [JeanPark96/Personal_Info_management_SW2018#5]
scanner.nextInt();다음에 scanner.nextLine();사용할 경우 먹힐 수 있음.
나는 update, delete에서 계속 먹혀서 전부 다 next()사용해줬어
![image](https://user-images.githubusercontent.com/37439958/48969804-1e824c00-f047-11e8-93e2-1e034e23d0d7.png)

**Comment by JeanPark96** [comment]
그냥 scanner객체 따로 만들어주는게 낫지 않아?? 저렇게 하면 콘솔창에서 입력받을 때 불편해졌던걸로 기억하는데

**Comment by jjisol** [comment]
오류안나고 잘 돌아가던데?
