### ISSUE TITLE
git remote add origin URL.git 이후에  fatal 메세지 뜸

### ISSUE THREAD

**Issue by Zeusl** [JeanPark96/Personal_Info_management_SW2018#7]
git remote add origin URL.git 하고 나서 
fatal: remote origin already exists 라고 떴는데 이거 무시하고 해줘도 괜찮을까? 

![5f](https://user-images.githubusercontent.com/30151642/48983807-e78b6380-f136-11e8-8844-5b1c0adcd764.JPG)

**Comment by JeanPark96** [comment]
이미 그 이름의 원격저장소가 있다는거니까 무시해도 될것 같아. 푸쉬는 무사히 했지??

**Comment by Zeusl** [comment]
응응 푸쉬는 무사히 했어!
